version: '3.8'
services:
  mysql_auth:
    image: mysql:8.0
    container_name: mysql_auth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: auth_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_auth_data:/var/lib/mysql

  mongodb_user:
    image: mongo:5.0
    container_name: mongodb_user_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - '27017:27017'
    volumes:
      - mongodb_user_data:/data/db

  redis_cache:
    image: redis:6.2-alpine
    container_name: redis_cache_service
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_cache_data:/data

volumes:
  mysql_auth_data:
  redis_cache_data:
  mongodb_user_data:
